from pydantic import BaseModel, Field


# The 7 core assessment domains from the plan
ASSESSMENT_DOMAINS = [
    "HPI",              # History of Present Illness
    "ROS",              # Review of Systems
    "PMH",              # Past Medical History
    "Medications",
    "Allergies",
    "Social_History",
    "Family_History",
]


def depth_label(question_count: int) -> str:
    """Categorize how deeply a domain was explored based on question count."""
    if question_count == 0:
        return "Missed"
    if question_count == 1:
        return "Surface"
    if question_count <= 3:
        return "Explored"
    return "Deep"


def depth_score(question_count: int) -> float:
    """0-100 score reflecting depth of exploration within a single domain."""
    if question_count == 0:
        return 0.0
    if question_count == 1:
        return 50.0
    if question_count <= 3:
        return 80.0
    return 100.0


class DomainCoverage(BaseModel):
    """Tracking data for a single assessment domain."""
    domain: str
    covered: bool = False
    question_count: int = 0
    topics_asked: list[str] = Field(default_factory=list)

    @property
    def depth(self) -> str:
        return depth_label(self.question_count)

    @property
    def depth_score(self) -> float:
        return depth_score(self.question_count)


class AssessmentResult(BaseModel):
    """Overall assessment coverage result for a session."""
    domains: dict[str, DomainCoverage] = Field(default_factory=dict)
    coverage_score: float = Field(0.0, description="Depth-weighted coverage score (0-100)")
    total_questions: int = 0

    def get_covered_domains(self) -> list[str]:
        return [d for d, cov in self.domains.items() if cov.covered]

    def get_missed_domains(self) -> list[str]:
        return [d for d, cov in self.domains.items() if not cov.covered]

    def get_depth_breakdown(self) -> dict[str, str]:
        """Return {domain: depth_label} for all domains."""
        return {d: cov.depth for d, cov in self.domains.items()}


class FeedbackReport(BaseModel):
    """Post-session feedback generated by the LLM."""
    session_id: str
    overall_score: float = Field(..., ge=0, le=100)
    domains_covered: list[str]
    domains_missed: list[str]
    strengths: list[str] = Field(default_factory=list, description="What the student did well")
    improvements: list[str] = Field(default_factory=list, description="Specific suggestions")
    critical_findings_caught: list[str] = Field(default_factory=list)
    critical_findings_missed: list[str] = Field(default_factory=list)
    diagnosis: str = Field(..., description="The actual diagnosis revealed")
    differential_diagnoses: list[str] = Field(default_factory=list)
    turn_highlights: list[dict] = Field(
        default_factory=list,
        description="Notable conversation turns with commentary"
    )
    summary: str = Field("", description="Overall narrative summary of performance")
